### ISSUE TITLE
Can't Update Launcher

### ISSUE THREAD

**Issue by Kie9029** [IllusionMods/IllusionLaunchers#1]
![image](https://user-images.githubusercontent.com/69164200/89210952-387d7b80-d5eb-11ea-8da2-84602f186483.png)

**Comment by ScrewThisNoise** [comment]
That is due to a outdated version of KKManager. Please download the newest KKManager from [](https://github.com/IllusionMods/KKManager/releases), then extract it to the '[UTILITY] KKManager' folder inside your game folder.

Not error with launcher, closing issue
