### ISSUE TITLE
Cant save settings 

### ISSUE THREAD

**Issue by jairochido** [IllusionMods/IllusionLaunchers#19]
i applied the latest version but now neither koikatsu or honey select 2 save settings, and the launcher doesnt open the game or studio, in both i gopt the error /userdata/setup.xml was corrupted , i tried to move the file and the error disappears , but the game still doesnt save the settings and cant be opened via the launcher, both games can be opened via the normal exe but, the setting are the default ones, 720 and windowed

**Comment by XHxiaohuaXH** [comment]
我也有同样的问题

**Comment by ScrewThisNoise** [comment]
Fixed and replaced the current release. Please redownload
