### ISSUE TITLE
HoneySelect 1 "Start BattleArena" Launches Main Game

### ISSUE THREAD

**Issue by PAdresse** [IllusionMods/IllusionLaunchers#4]
The "Start BattleArena" Button of the HoneySelect 1 Launcher (v3.0.1) actually starts the main game.
After quick look at https://github.com/IllusionMods/IllusionLaunchers/blob/master/src/HoneySelect/MainWindow.xaml.cs#L264 I cant find a _Click function for that button, so I guess it's just missing by accident?

**Comment by ScrewThisNoise** [comment]
Fixed in commit 54e1580
